### ISSUE TITLE
Rails 4 compatible?

### ISSUE THREAD

**Issue by tj8295** [paypal/merchant-sdk-ruby#10]
I'm having trouble finding documentation on this gem as to whether it is compatible with rails 4.

**Comment by juwlee** [comment]
Unfortunately, there is [some backward compatibility issue](https://github.com/paypal/merchant-sdk-ruby/pull/16#issuecomment-54171388) that blocks us from supporting Rails 4+. [The note](https://github.com/paypal/merchant-sdk-ruby#configuration) has been added to main README.

**Comment by dkreft** [comment]
What does PayPal recommend for Rails 4, then? Is a fix in the works?
