### ISSUE TITLE
UpdateRecurringPaymentsProfile

### ISSUE THREAD

**Issue by chamnap** [paypal/merchant-sdk-ruby#20]
In the sample app, there is missing example on `UpdateRecurringPaymentsProfile`. I'm not really sure what to send to PayPal API, and the request options to send.

Can anyone give me an example?

**Comment by juwlee** [comment]
@chamnap please see [this doc](https://developer.paypal.com/webapps/developer/docs/classic/api/merchant/UpdateRecurringPaymentsProfile_API_Operation_NVP/) for reference.
