### ISSUE TITLE
v1.117.0 is not available in Rubygems

### ISSUE THREAD

**Issue by adamniedzielski** [paypal/merchant-sdk-ruby#21]
Please check https://rubygems.org/gems/paypal-sdk-merchant
It looks like v1.117.0 was not pushed to Rubygems.

**Comment by juwlee** [comment]
@adamniedzielski Thanks for pointing it out. `v1.117.0` was yanked but a newer version (`[v1.117.1](https://rubygems.org/gems/paypal-sdk-merchant/versions/1.117.1): no code change) has been released.
