### ISSUE TITLE
Deprecation notice clarification

### ISSUE THREAD

**Issue by morgoth** [paypal/merchant-sdk-ruby#23]
The readme states "This Classic SDK is not actively supported and will be deprecated in the future."
Does it mean that classic paypal API will be deprecated in some time as well?

Currently I'm using activemerchant and I would like to migrate to this gem, but this note is not welcoming :-(

**Comment by Chocksy** [comment]
I'm not sure why there is no response to this. I asked yesterday this on stackoverflow: http://stackoverflow.com/questions/32637626/how-can-i-use-the-mass-pay-api-with-the-new-rest-api-in-ruby

Maybe we can get some answers from paypal there. I asked paypal support about this but they have no idea of when this will get deprecated and how to use the mass payment api with the new rest api. ... :(

**Comment by ppmtscory** [comment]
The idea is that anything 'new' will be using our new REST APIs.  However, with that being said, those API sets have to be at parity to legacy functionality before anybody would feel comfortable deprecating the Classic APIs.  There is no hard date set for deprecation, but priorities are set as such that only major bug fixes will get attention and not necessarily any new enhancements.  We're shifting priority for new enhancements over to the REST APIs.  

Our [Payout APIs](https://developer.paypal.com/docs/payouts/) are the RESTful equivalent to the classic MassPay.

**Comment by Chocksy** [comment]
@ppmtscory thanks for the reply that was fast. :) :+1: i'm glad to hear that that means i'll have to keep an eye on what you guys provide. We actually need permissions + masspay as i say in the question on stack.

**Comment by ppmtscory** [comment]
@Chocksy I replied on your Stack issue as well  :)
