### ISSUE TITLE
Need for Subject Parameter

### ISSUE THREAD

**Issue by bnelson365** [paypal/merchant-sdk-ruby#24]
I need to use the Subject parameter for use with third party permissions. This is something that is available in the PHP version (https://github.com/paypal/merchant-sdk-php/blob/473737430f54835b9d55e99f965546c6de4470ff/samples/Configuration.php). Any help would be greatly appreciated.

**Comment by andrykonchin** [comment]
You is able to specify `subject` like any other credentials in config file after other ones `username`, `password` and `signature`.

**Comment by jaypatel512** [comment]
As @andrykonchin said, you should be able to pass subject as usual. [Ruby SDK supports that](https://github.com/paypal/sdk-core-ruby/blob/master/lib/paypal-sdk/core/config.rb#L72).
