### ISSUE TITLE
TypeError: invalid data when OfferCouponInfo is an array

### ISSUE THREAD

**Issue by adamniedzielski** [paypal/merchant-sdk-ruby#27]
In our application we have the concept of "Adjustment" which reduces "Order" total price. We specify adjustments when calling `build_set_express_checkout` method, passing them as `PaymentDetailsItem` with the negative amount. This works fine and the customers are able to pay the correct total price.

However, we receive the following error when calling `get_transaction_details` method for transactions which have more than one adjustment:

```
TypeError: invalid data([{"Type"=>nil, "ID"=>nil, "Amount"=>"18.69", "AmountCurrency"=>"GBP"}, {"Type"=>nil, "ID"=>nil, "Amount"=>"37.26", "AmountCurrency"=>"GBP"}]) for PayPal::SDK::Merchant::DataTypes::OfferCouponInfoType
```

Take a look at the raw response from the API (before `paypal-sdk-merchant` tries to parse them):

``` ruby
# no adjustments
"OfferCouponInfo"=>{"Type"=>nil, "ID"=>nil, "Amount"=>nil, "AmountCurrency"=>nil}

#1 adjustment
"OfferCouponInfo"=>{"Type"=>nil, "ID"=>nil, "Amount"=>"33.95", "AmountCurrency"=>"GBP"}

#2 adjustments
"OfferCouponInfo"=>[{"Type"=>nil, "ID"=>nil, "Amount"=>"18.69", "AmountCurrency"=>"GBP"}, {"Type"=>nil, "ID"=>nil, "Amount"=>"37.26", "AmountCurrency"=>"GBP"}]
```

The API is returning an array when there are two adjustments, but the library always expects a single object - https://github.com/paypal/merchant-sdk-ruby/blob/a24594123966a8e14ac47bc0620f1f951d966f76/lib/paypal-sdk/merchant/data_types.rb#L1675

I don't know whether this is an expected behavior on the API side. As far as I can tell, in the library code there is no support for the fields which can be an object or an array of objects.

**Comment by pauloschilling** [comment]
Same here.

_Let's celebrate 2 years of an unsolved issue._ 🎉 ... 😞

**Comment by xiaoleih41** [comment]
In this case, you may consider to look into line item detail instead of offer coupon Info.

**Comment by pauloschilling** [comment]
The error is raised when the API response is validated/parsed by the SDK, in our case it happens when we call `#get_transaction_details`, and we don't even use the `OfferCouponInfo` attribute.

**Comment by xiaoleih41** [comment]
It looks like SDK doesn't handle the array. Is that possible as a workaround, pass the discount through line item instead?

**Comment by pauloschilling** [comment]
@xiaoleih41 that's exactly the way we're doing to handle our discounts, using an item for it, but recently we had a marketing partnership with PayPal and they added a discount on their side, causing the API to return this:

```rb
OfferCouponInfo = [
  {"Type"=>"OFFER", "ID"=>"XXXXXXXXXXXXXXXX", "Amount"=>"15.00", "AmountCurrency"=>"BRL"},
  {"Type"=>"OFFER", "ID"=>"YYYYYYYYYYYYYYYY", "Amount"=>"15.00", "AmountCurrency"=>"BRL"},
  {"Type"=>"OFFER", "ID"=>"ZZZZZZZZZZZZZZZZ", "Amount"=>"15.00", "AmountCurrency"=>"BRL"}
]
```

Not sure why the API is returning an array with 3 items, since each order/transaction was eligible to only one discount of 15.00 BRL.

Unfortunately, we do not have control over this behavior.

**Comment by xiaoleih41** [comment]
Can you give me a  **debugID**?

**Comment by xiaoleih41** [comment]
Close due to inactivity. This SDK has been deprecated. please refer to newer PayPal REST API for future integration.
