### ISSUE TITLE
Unable send Payer information to paypal

### ISSUE THREAD

**Issue by zapbuild** [paypal/merchant-sdk-ruby#30]
Hello,
I was just trying to  send the customer’s info to be stored in the payPal credit card system. PayPal has sections for name, address, city etc, email, phone, and there must be a way to communicate to PayPal the name of the product and the size of the shirt.

Please help. 
Thanks!

**Comment by jaypatel512** [comment]
For future reference, please reach out to [PayPal Technical Support](https://www.paypal-techsupport.com/) for API related questions.
