### ISSUE TITLE
PayPal::SDK::Core::Exceptions::ServerError when verification IPN message with ipn_valid? (production)

### ISSUE THREAD

**Issue by avidmaulanas** [paypal/merchant-sdk-ruby#34]
Hi,
I am trying to verification IPN message with this code `@api.ipn_valid?(request.raw_post)` and work properly, but sometimes get an error like this `PayPal::SDK::Core::Exceptions::ServerError` Failed. Response code = 503. Response message = Service Unavailable

Anyone have this error like this? I need your help
Thank you :)

**Comment by pp-randy** [comment]
Sorry for the delay @avidmaulanas.  Are you still seeing this issue sporadically?
